name: Test workflow

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  pull_request_target:
    types: [closed]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: changes
        uses: tj-actions/changed-files@fix/bug-with-similar-commits-when-github-event-before-is-empty
        id: changes
        with:
          since_last_remote_commit: 'true'
          dir_names: 'true'
          json: 'true'

      - name: Show output
        run: |
          echo '${{ steps.changes.outputs.all_changed_files }}'
